//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTravel.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars_status
    {
        public int carStatusId { get; set; }
        public int carId { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public string toDate { get; set; }
        public bool isAvailble { get; set; }
    
        public virtual cars cars { get; set; }
    }
}
