//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTravel.Main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarTravelDb : DbContext
    {
        public CarTravelDb()
            : base("name=CarTravelDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<cars_status> cars_status { get; set; }
        public virtual DbSet<cars_status_list> cars_status_list { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
        public virtual DbSet<reservations_cars> reservations_cars { get; set; }
        public virtual DbSet<reservations_status> reservations_status { get; set; }
        public virtual DbSet<systemusers> systemusers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
