//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTravel.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservations_cars
    {
        public int reservationCarId { get; set; }
        public long reservationId { get; set; }
        public int carId { get; set; }
    }
}
